rebuild errors
bitfinexcom/bfx-facs-grc pull request #17
Opened 2023-11-16 00:29 UTC by batrudinych

2023-11-16 12:59 UTC, tarcisiozf approved these changes

2023-11-23 12:09 UTC, vigan-abd requested changes

2023-11-23 12:09 UTC, vigan-abd commented on lib.js
> +const buildErr = err => err ? new Error(err.message || err) : null
isn't this hiding the original error trace?

2023-11-23 12:09 UTC, vigan-abd commented on lib.js
> +'use strict'
this file is more like util, I would prefer to have lib/util.js instead

2023-11-23 12:09 UTC, vigan-abd commented on lib.js
> +const getErr = err => _.isString(err) ? new Error(err) : err
both utils are similar so I would opt in to have just getErr and adjust  `if (isPromise) {...` section to use getError when error is not nil

2023-11-29 17:03 UTC, vigan-abd commented on lib/utils.js
> +const buildErr = err => err ? new Error(err.message || err) : null
so based on here https://github.com/bitfinexcom/bfx-facs-grc/pull/17#discussion_r1409608557 my thought is this:
const buildErr = (err) => err ? (err instanceof Error ? err : new Error(err)) : null

2023-11-29 17:22 UTC, vigan-abd commented on lib/utils.js
> +const buildErr = err => err ? new Error(err.message || err) : null
well we always lost error trace so this is techinicaly an improvement

2023-12-08 11:17 UTC, vigan-abd approved these changes

2023-12-08 14:09 UTC, merged